#!/usr/bin/env python3
"""
crossval.py — cross-validation of the symbolic C model against an
independent state-vector simulator (dependency-free Python).

Purpose (threats-to-validity mitigation): the verdicts produced by ESBMC
are relative to the C model generated by qsharp2c.py. This script checks,
for every experiment in the paper, that an independent implementation of
the gate semantics (complex matrices applied to state vectors, as in any
standard simulator such as Qiskit's statevector backend) agrees with the
states and properties encoded in the harness assertions. It additionally
validates the exact Z[w] ring encoding against complex arithmetic.

This is sampling-based evidence over the fixed initial states used in the
experiments; the formal soundness argument for the transpilation remains
future work (see the paper, Section "Threats to Validity").

Usage: python3 scripts/crossval.py
"""

import cmath
import math
import sys

SQ2 = 1 / math.sqrt(2)

# --------------------------------------------------------------------------
# Independent state-vector simulator (qubit 0 = most significant bit).
# --------------------------------------------------------------------------

H = [[SQ2, SQ2], [SQ2, -SQ2]]
X = [[0, 1], [1, 0]]
S = [[1, 0], [0, 1j]]
T = [[1, 0], [0, cmath.exp(1j * math.pi / 4)]]


def apply_1q(state, gate, q, n):
    """Apply a 1-qubit gate to qubit q of an n-qubit state vector."""
    out = [0j] * len(state)
    bit = 1 << (n - 1 - q)
    for i, amp in enumerate(state):
        b = 1 if i & bit else 0
        for b2 in (0, 1):
            j = (i & ~bit) | (bit if b2 else 0)
            out[j] += gate[b2][b] * amp
    return out


def apply_cnot(state, c, t, n):
    out = list(state)
    cbit, tbit = 1 << (n - 1 - c), 1 << (n - 1 - t)
    for i in range(len(state)):
        if i & cbit:
            out[i] = state[i ^ tbit]
    return out


def basis(n, idx=0):
    v = [0j] * (1 << n)
    v[idx] = 1 + 0j
    return v


def close(u, v, tol=1e-12):
    return all(abs(a - b) <= tol for a, b in zip(u, v))


# --------------------------------------------------------------------------
# Exact Z[w] encoding (mirrors harness_1q_exact.c) evaluated numerically.
# --------------------------------------------------------------------------

W = cmath.exp(1j * math.pi / 4)


def zw_value(c, k):
    """Numeric value of (c0 + c1 w + c2 w^2 + c3 w^3) / sqrt(2)^k."""
    return sum(c[i] * W**i for i in range(4)) / (math.sqrt(2) ** k)


def exact_H(state):
    (a, b, k) = state
    return ([a[i] + b[i] for i in range(4)],
            [a[i] - b[i] for i in range(4)], k + 1)


def exact_S(state):
    (a, b, k) = state
    return (a, [-b[2], -b[3], b[0], b[1]], k)


def exact_T(state):
    (a, b, k) = state
    return (a, [-b[3], b[0], b[1], b[2]], k)


# --------------------------------------------------------------------------
# Checks (one per experiment plus ring validation and GHZ).
# --------------------------------------------------------------------------

def checks():
    results = []

    def check(name, ok):
        results.append((name, ok))

    # Exp 1: X.X = I on |0>
    st = apply_1q(apply_1q(basis(1), X, 0, 1), X, 0, 1)
    check("Exp 1  X.X = I on |0>", close(st, basis(1)))

    # Exp 2a: H.H = I on |0>
    st = apply_1q(apply_1q(basis(1), H, 0, 1), H, 0, 1)
    check("Exp 2a H.H = I on |0>", close(st, basis(1)))

    # Exp 2b: CNOT.CNOT = I on |00>
    st = apply_cnot(apply_cnot(basis(2), 0, 1, 2), 0, 1, 2)
    check("Exp 2b CNOT.CNOT = I on |00>", close(st, basis(2)))

    # Exp 3: Bell amplitudes (|00> + |11>)/sqrt(2)
    st = apply_cnot(apply_1q(basis(2), H, 0, 2), 0, 1, 2)
    bell = [SQ2, 0, 0, SQ2]
    check("Exp 3  Bell = (|00>+|11>)/sqrt(2)", close(st, bell))

    # Exp 4: S.S on |1> must NOT be |1> (deliberate fault confirmed:
    # the simulator agrees the asserted property is genuinely violated).
    st = apply_1q(apply_1q(basis(1, 1), S, 0, 1), S, 0, 1)
    check("Exp 4  S.S|1> = -|1> (fault is real)",
          close(st, [0j, -1 + 0j]) and not close(st, basis(1, 1)))

    # Exp 5: QRNG uniformity after H|0>
    st = apply_1q(basis(1), H, 0, 1)
    p0, p1 = abs(st[0]) ** 2, abs(st[1]) ** 2
    check("Exp 5  QRNG P(0) = P(1) = 1/2",
          abs(p0 - 0.5) < 1e-12 and abs(p1 - 0.5) < 1e-12)

    # Exp 6: H.T.T = H.S on |0>
    st_t = apply_1q(apply_1q(apply_1q(basis(1), H, 0, 1), T, 0, 1), T, 0, 1)
    st_s = apply_1q(apply_1q(basis(1), H, 0, 1), S, 0, 1)
    check("Exp 6  H.T.T = H.S on |0>", close(st_t, st_s))

    # Exact ring encoding vs complex arithmetic on the Exp 6 circuit.
    zero = ([1, 0, 0, 0], [0, 0, 0, 0], 0)
    ex = exact_T(exact_T(exact_H(zero)))
    ex_alpha, ex_beta = zw_value(ex[0], ex[2]), zw_value(ex[1], ex[2])
    check("Ring   Z[w] encoding == complex semantics (H,T,T)",
          abs(ex_alpha - st_t[0]) < 1e-12 and abs(ex_beta - st_t[1]) < 1e-12)

    ex_s = exact_S(exact_H(zero))
    check("Ring   Z[w] equivalence T.T = S is exact",
          exact_T(exact_T(exact_H(zero))) == ex_s)

    # GHZ-n states used by the scalability benchmark.
    for n in (2, 4, 8):
        st = apply_1q(basis(n), H, 0, n)
        for q in range(n - 1):
            st = apply_cnot(st, q, q + 1, n)
        ghz = [0j] * (1 << n)
        ghz[0] = ghz[-1] = SQ2 + 0j
        check(f"GHZ-{n} amplitudes = (|0..0>+|1..1>)/sqrt(2)", close(st, ghz))

    return results


def main():
    results = checks()
    width = max(len(name) for name, _ in results)
    failed = 0
    for name, ok in results:
        print(f"{name:<{width}}  {'PASS' if ok else 'FAIL'}")
        failed += 0 if ok else 1
    print("-" * (width + 6))
    if failed:
        print(f"{failed} check(s) FAILED")
        sys.exit(1)
    print(f"all {len(results)} cross-validation checks passed")


if __name__ == "__main__":
    main()
